- hosts: all
  sudo: True
  tasks:
  - name: install MariaDB
    yum: name=mariadb-server

  # TODO: Fix my.conf if this check fails
  # Note: The default one of CentOS7 clould image is InnoDB
  - name: Check if the default storage engine is InnoDB
    shell: mysql -e "show engines" | grep "DEFAULT" | awk '{ print $1 }'
    register: default_engine
    failed_when: default_engine.rc != 0 or default_engine.stdout != "InnoDB"
    changed_when: default_engine.stdout != "InnoDB"

  - name: start MariaDB
    service: name=mariadb state=started enabled=yes
