- hosts: all
  vars:
    db_name: hatohol
    db_login_user: hatohol
    db_login_password: hatohol
    hatohol_conf_path: hatohol.conf
    db_server: localhost

  sudo: True
  tasks:
  - include: setup-repos.yaml
  - name: install hatohol-server
    yum: name=hatohol-server state=latest

  - name: copy configuration file
    copy: src={{ hatohol_conf_path }} dest=/etc/hatohol/hatohol.conf
    when: db_server != 'localhost'

  - name: check if DB exists
    shell: mysql -h {{ db_server }} -u{{ db_login_user }} -p{{ db_login_password }} -N -e "show databases LIKE '{{ db_name }}'"
    register: dblist
    failed_when: dblist.rc != 0
    changed_when: False

  #- debug: var=dblist
  #- debug: var=dblist.stdout

  - name: initialize Hatohol DB
    command: hatohol-db-initiator --db-user {{ db_login_user }} --db-password {{ db_login_password }} -s
    when: "dblist.stdout != '{{ db_name }}'"

  - name: launch Hatohol server
    service: name=hatohol state=started enabled=yes
