- hosts: all
  sudo: True
  tasks:

  - name: install epel repository
    yum: name=epel-release

  - name: install RabbitMQ server
    yum: name=rabbitmq-server

  - name: launch RabbitMQ server
    service: name=rabbitmq-server state=started enabled=yes

